### ISSUE TITLE
JS-Error on Read-Only Extension on disable_forums_functions

### ISSUE THREAD

**Issue by BerndGewehr** [hclcnx/global-samples#36]
`Uncaught ReferenceError: disable_forum_functions is not defined
    at disable-icc-content-creation.js:20
    at nrWrapper (communitystart:385)`

Appears in just one community, not in all...

**Comment by BerndGewehr** [comment]
This error appears only on community overview pages in horizontal layouts, that classic left sidebar layouts work fine.

**Comment by BerndGewehr** [comment]
@padraic-edwards @MartinDonnelly can you have a look?

**Comment by andrehagemeier** [comment]
Hi Bernd,
thanks for letting us know but with the Cloud going EOS in a couple of days, we don't think it is extremely urgent to fix this problem. We would rather  discuss a proper readonly mode at a later time.
Thanks
Andre

**Comment by BerndGewehr** [comment]
Ok @andrehagemeier thank you for the feedback!
