### ISSUE TITLE
Read only Extension hides some useful stuff and does not hide all create buttons in horizontal community layout in german

### ISSUE THREAD

**Issue by BerndGewehr** [hclcnx/global-samples#37]
Many buttons still visible, content creation still possible while e. g. links to wiki pages in rich text widgets on community homepages are hidden.

Please correct this useful feature ASAP, it could actually help doing a seamless migration!

**Comment by BerndGewehr** [comment]
![image](https://user-images.githubusercontent.com/21081707/87151817-ce580c00-c2b4-11ea-974c-f6045a590fd4.png)

**Comment by BerndGewehr** [comment]
@andrehagemeier please have a look

**Comment by BerndGewehr** [comment]
Without extension:
![image](https://user-images.githubusercontent.com/21081707/87153790-51c72c80-c2b8-11ea-9aad-0bbcd53b8dde.png)

With extension:
![image](https://user-images.githubusercontent.com/21081707/87153876-77543600-c2b8-11ea-8aeb-8aa543a89a58.png)

**Comment by BerndGewehr** [comment]
Create links stay usable:
![image](https://user-images.githubusercontent.com/21081707/87153972-abc7f200-c2b8-11ea-878f-d0111aed0103.png)

**Comment by BerndGewehr** [comment]
The idea of the widget is great - but the current code state is not really usable.

**Comment by andrehagemeier** [comment]
Hi Bernd,
thanks for letting us know but with the Cloud going EOS in a couple of days, we don't think it is extremely urgent to fix this problem. We would rather  discuss a proper readonly mode at a later time.
Thanks
Andre
